import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import {
  Building2,
  Calendar,
  FileText,
  Mail,
  Search,
  Send,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/imperium/page-header";
import { StatusBadge } from "@/components/imperium/status-badge";
import { MatchScore } from "@/components/imperium/match-score";
import { getApplications } from "@/lib/imperium/client";
import { artifactUrl } from "@/lib/imperium/client";
import {
  APPLICATION_STATUS_ORDER,
  formatRelativeTime,
} from "@/lib/imperium/format";

export const Route = createFileRoute("/applications")({
  head: () => ({
    meta: [
      { title: "Applications — Imperium" },
      {
        name: "description",
        content:
          "Track every Imperium application: status, match score, resume, cover letter and timeline.",
      },
      { property: "og:title", content: "Applications — Imperium" },
      { property: "og:description", content: "Full application lifecycle tracking." },
    ],
  }),
  component: ApplicationsPage,
});

function ApplicationsPage() {
  const { data, isLoading, error } = useQuery({
    queryKey: ["applications", { limit: 500 }],
    queryFn: ({ signal }) => getApplications({ limit: 500 }, signal),
    retry: false,
    refetchInterval: 20_000,
  });

  const [q, setQ] = useState("");
  const [status, setStatus] = useState<string | null>(null);

  const apps = data ?? [];

  const countsByStatus = useMemo(() => {
    const m = new Map<string, number>();
    APPLICATION_STATUS_ORDER.forEach((s) => m.set(s, 0));
    apps.forEach((a) => m.set(a.status, (m.get(a.status) ?? 0) + 1));
    return m;
  }, [apps]);

  const filtered = useMemo(() => {
    return apps.filter((a) => {
      if (status && a.status !== status) return false;
      if (q) {
        const t = q.toLowerCase();
        return (
          a.job_title?.toLowerCase().includes(t) ||
          a.company?.toLowerCase().includes(t)
        );
      }
      return true;
    });
  }, [apps, q, status]);

  return (
    <div className="mx-auto w-full max-w-7xl space-y-5 p-4 md:p-6">
      <PageHeader
        title="Application Tracker"
        description="Every application package generated by Imperium, with full lifecycle status."
        actions={
          <Button asChild className="bg-gradient-primary text-primary-foreground hover:opacity-95">
            <Link to="/search">
              <Send className="mr-2 h-4 w-4" /> New Search
            </Link>
          </Button>
        }
      />

      <div className="grid grid-cols-2 gap-2 md:grid-cols-6">
        {[
          { label: "Total", value: apps.length, key: null as string | null },
          ...APPLICATION_STATUS_ORDER.map((s) => ({
            label: s,
            value: countsByStatus.get(s) ?? 0,
            key: s,
          })),
        ].map((c) => (
          <button
            key={c.label}
            onClick={() => setStatus(c.key)}
            className={`rounded-lg border p-3 text-left transition-all ${
              status === c.key
                ? "border-primary bg-primary/10"
                : "border-border bg-card hover:border-primary/40"
            }`}
          >
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
              {c.label}
            </div>
            <div className="mt-0.5 text-xl font-semibold tabular-nums">
              {c.value}
            </div>
          </button>
        ))}
      </div>

      <Card>
        <CardContent className="p-3">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search by title or company…"
              value={q}
              onChange={(e) => setQ(e.target.value)}
              className="pl-8"
            />
          </div>
        </CardContent>
      </Card>

      {isLoading ? (
        <EmptyCard text="Loading applications…" />
      ) : error ? (
        <EmptyCard text="Cannot reach Imperium backend." tone="error" />
      ) : filtered.length === 0 ? (
        <EmptyCard text="No applications match your filter. Run a job search to create application packages." />
      ) : (
        <div className="space-y-3">
          {filtered.map((a) => (
            <Card key={a.application_id} className="overflow-hidden">
              <CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center">
                <MatchScore score={a.match_score} />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                    <h3 className="text-sm font-semibold">{a.job_title}</h3>
                    <StatusBadge status={a.status} />
                  </div>
                  <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-0.5 text-xs text-muted-foreground">
                    <span className="inline-flex items-center gap-1">
                      <Building2 className="h-3 w-3" /> {a.company}
                    </span>
                    <span className="inline-flex items-center gap-1">
                      <Calendar className="h-3 w-3" />{" "}
                      {formatRelativeTime(a.date_applied)}
                    </span>
                    {a.last_updated && (
                      <span>updated {formatRelativeTime(a.last_updated)}</span>
                    )}
                  </div>
                  {a.notes && (
                    <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">
                      {a.notes}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 flex-wrap gap-2">
                  {a.resume_path && (
                    <Button asChild variant="outline" size="sm">
                      <a
                        href={artifactUrl(a.resume_path)}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <FileText className="mr-1.5 h-3.5 w-3.5" /> Resume
                      </a>
                    </Button>
                  )}
                  {a.cover_letter_path && (
                    <Button asChild variant="outline" size="sm">
                      <a
                        href={artifactUrl(a.cover_letter_path)}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <Mail className="mr-1.5 h-3.5 w-3.5" /> Cover Letter
                      </a>
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function EmptyCard({
  text,
  tone = "muted",
}: {
  text: string;
  tone?: "muted" | "error";
}) {
  return (
    <Card
      className={
        tone === "error"
          ? "border-destructive/30 bg-destructive/5"
          : "border-dashed"
      }
    >
      <CardContent className="p-10 text-center text-sm text-muted-foreground">
        {text}
      </CardContent>
    </Card>
  );
}
