import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import {
  Building2,
  Calendar,
  FileText,
  Mail,
  Search,
  Send,
  ShieldCheck,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/imperium/page-header";
import { StatusBadge } from "@/components/imperium/status-badge";
import { MatchScore } from "@/components/imperium/match-score";
import { fetchArtifactText, getApplications } from "@/lib/imperium/client";
import { APPLICATION_STATUS_ORDER, formatRelativeTime } from "@/lib/imperium/format";

export const Route = createFileRoute("/_authenticated/applications")({
  head: () => ({
    meta: [
      { title: "Applications — Imperium" },
      {
        name: "description",
        content:
          "Track every Imperium application: status, match score, resume, cover letter and review gate.",
      },
      { property: "og:title", content: "Applications — Imperium" },
      { property: "og:description", content: "Full application lifecycle tracking." },
    ],
  }),
  component: ApplicationsPage,
});

function ApplicationsPage() {
  const { data, isLoading, error } = useQuery({
    queryKey: ["applications", { limit: 500 }],
    queryFn: ({ signal }) => getApplications({ limit: 500 }, signal),
    retry: false,
    refetchInterval: 5_000,
  });

  const [q, setQ] = useState("");
  const [status, setStatus] = useState<string | null>(null);
  const apps = data ?? [];

  const countsByStatus = useMemo(() => {
    const m = new Map<string, number>();
    APPLICATION_STATUS_ORDER.forEach((s) => m.set(s, 0));
    apps.forEach((a) => m.set(a.status, (m.get(a.status) ?? 0) + 1));
    return m;
  }, [apps]);

  const filtered = useMemo(() => {
    return apps.filter((a) => {
      if (status && a.status !== status) return false;
      if (q) {
        const t = q.toLowerCase();
        return (
          a.job_title?.toLowerCase().includes(t) ||
          a.company?.toLowerCase().includes(t)
        );
      }
      return true;
    });
  }, [apps, q, status]);

  const pendingCount = countsByStatus.get("Preparing") ?? 0;

  const downloadResume = async (path: string, idShort: string) => {
    const content = await fetchArtifactText(path);
    const { downloadResumePdf } = await import("@/lib/imperium/resume-render");
    await downloadResumePdf(content, "classic", `resume_${idShort}.pdf`);
  };
  const downloadCover = async (path: string, idShort: string, company: string, candidate: string) => {
    const content = await fetchArtifactText(path);
    const { downloadCoverLetterPdf } = await import("@/lib/imperium/resume-render");
    await downloadCoverLetterPdf(
      { candidate_name: candidate || "Candidate", company: company || "Company", body: content },
      `cover-letter_${idShort}.pdf`,
    );
  };

  return (
    <div className="mx-auto w-full max-w-7xl space-y-5 p-4 md:p-6">
      <PageHeader
        title="Application Tracker"
        description="Every application package generated by Imperium, with review gates and full lifecycle status."
        actions={
          <Button asChild className="bg-gradient-primary text-primary-foreground hover:opacity-95">
            <Link to="/search">
              <Send className="mr-2 h-4 w-4" /> New Search
            </Link>
          </Button>
        }
      />

      {pendingCount > 0 && (
        <Card className="border-warning/40 bg-warning/5">
          <CardContent className="flex items-center gap-3 p-4">
            <ShieldCheck className="h-6 w-6 text-warning" />
            <div className="flex-1">
              <div className="text-sm font-semibold">
                {pendingCount} application{pendingCount > 1 ? "s" : ""} awaiting your approval
              </div>
              <div className="text-xs text-muted-foreground">
                Imperium will never submit without your final review.
              </div>
            </div>
            <Button
              size="sm"
              onClick={() => setStatus("Preparing")}
              className="bg-warning text-warning-foreground hover:opacity-90"
            >
              Show pending
            </Button>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-2 gap-2 md:grid-cols-8">
        {[
          { label: "Total", value: apps.length, key: null as string | null },
          ...APPLICATION_STATUS_ORDER.map((s) => ({
            label: s, value: countsByStatus.get(s) ?? 0, key: s,
          })),
        ].map((c) => (
          <button
            key={c.label}
            onClick={() => setStatus(c.key)}
            className={`rounded-lg border p-2.5 text-left transition-all ${
              status === c.key
                ? "border-primary bg-primary/10"
                : "border-border bg-card hover:border-primary/40"
            }`}
          >
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground truncate">
              {c.label}
            </div>
            <div className="mt-0.5 text-xl font-semibold tabular-nums">{c.value}</div>
          </button>
        ))}
      </div>

      <Card>
        <CardContent className="p-3">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search by title or company…"
              value={q}
              onChange={(e) => setQ(e.target.value)}
              className="pl-8"
            />
          </div>
        </CardContent>
      </Card>

      {isLoading ? (
        <EmptyCard text="Loading applications…" />
      ) : error ? (
        <EmptyCard text="Cannot reach Imperium backend." tone="error" />
      ) : filtered.length === 0 ? (
        <EmptyCard text="No applications match your filter. Run a job search to create application packages." />
      ) : (
        <div className="space-y-3">
          {filtered.map((a) => {
            const isPending = a.status === "Preparing";
            return (
              <Card key={a.application_id} className={isPending ? "border-warning/40" : "overflow-hidden"}>
                <CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center">
                  <MatchScore score={a.match_score} />
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                      <h3 className="text-sm font-semibold">{a.job_title}</h3>
                      <StatusBadge status={a.status} />
                    </div>
                    <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-0.5 text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Building2 className="h-3 w-3" /> {a.company}
                      </span>
                      <span className="inline-flex items-center gap-1">
                        <Calendar className="h-3 w-3" />{" "}
                        {formatRelativeTime(a.date_applied)}
                      </span>
                      {a.last_updated && (
                        <span>updated {formatRelativeTime(a.last_updated)}</span>
                      )}
                    </div>
                    {(a.matched_skills?.length ?? 0) > 0 && (
                      <div className="mt-1.5 flex flex-wrap gap-1">
                        {a.matched_skills!.slice(0, 6).map((s) => (
                          <span
                            key={s}
                            className="rounded bg-success/10 px-1.5 py-0.5 text-[10px] text-success"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="flex shrink-0 flex-wrap gap-2">
                    {isPending && (
                      <Button asChild size="sm" className="bg-warning text-warning-foreground hover:opacity-90">
                        <Link to="/review/$id" params={{ id: a.application_id }}>
                          <ShieldCheck className="mr-1.5 h-3.5 w-3.5" /> Review
                        </Link>
                      </Button>
                    )}
                    {a.resume_path && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => downloadResume(a.resume_path!, a.application_id.slice(0, 8))}
                      >
                          <FileText className="mr-1.5 h-3.5 w-3.5" /> Resume PDF
                      </Button>
                    )}
                    {a.cover_letter_path && (
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => downloadCover(a.cover_letter_path!, a.application_id.slice(0, 8), a.company, "")}
                      >
                          <Mail className="mr-1.5 h-3.5 w-3.5" /> Cover Letter PDF
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}

function EmptyCard({ text, tone = "muted" }: { text: string; tone?: "muted" | "error" }) {
  return (
    <Card className={tone === "error" ? "border-destructive/30 bg-destructive/5" : "border-dashed"}>
      <CardContent className="p-10 text-center text-sm text-muted-foreground">{text}</CardContent>
    </Card>
  );
}
