/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicImperiumTestRouteImport } from './routes/api/public/imperium-test'
import { Route as AuthenticatedReviewIdRouteImport } from './routes/_authenticated/review.$id'

const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/_authenticated/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/_authenticated/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/_authenticated/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/_authenticated/applications',
    path: '/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/_authenticated/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImperiumTestRoute = ApiPublicImperiumTestRouteImport.update({
  id: '/api/public/imperium-test',
  path: '/api/public/imperium-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewIdRoute = AuthenticatedReviewIdRouteImport.update({
  id: '/_authenticated/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/activity': typeof AuthenticatedActivityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/api/public/imperium-test': typeof ApiPublicImperiumTestRoute
}
export interface FileRoutesByTo {
  '/activity': typeof AuthenticatedActivityRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/api/public/imperium-test': typeof ApiPublicImperiumTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/review/$id': typeof AuthenticatedReviewIdRoute
  '/api/public/imperium-test': typeof ApiPublicImperiumTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/activity'
    | '/applications'
    | '/dashboard'
    | '/jobs'
    | '/resume'
    | '/search'
    | '/settings'
    | '/review/$id'
    | '/api/public/imperium-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/applications'
    | '/dashboard'
    | '/jobs'
    | '/resume'
    | '/search'
    | '/settings'
    | '/review/$id'
    | '/api/public/imperium-test'
  id:
    | '__root__'
    | '/_authenticated/activity'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/resume'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/review/$id'
    | '/api/public/imperium-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedReviewIdRoute: typeof AuthenticatedReviewIdRoute
  ApiPublicImperiumTestRoute: typeof ApiPublicImperiumTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/imperium-test': {
      id: '/api/public/imperium-test'
      path: '/api/public/imperium-test'
      fullPath: '/api/public/imperium-test'
      preLoaderRoute: typeof ApiPublicImperiumTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review/$id': {
      id: '/_authenticated/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof AuthenticatedReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedReviewIdRoute: AuthenticatedReviewIdRoute,
  ApiPublicImperiumTestRoute: ApiPublicImperiumTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
